<?php
/**
 * Created by PhpStorm.
 * User: wanghaotian
 * Date: 2018/8/25
 * Time: 16:57
 * 对比两个数组不同的元素
 * 参考文档:https://blog.csdn.net/qazx123q/article/details/79634613
 */


//$str1="SJLYXX,ZYFL,DJSJ,LBCJ,GZDL,OBJ_ID,SGYJQXD_ID,BDZID,BDZMC,SSDSID,SSDSMC,GZXLID,GZXLMC,GZSB,GZSBMC,JSYY,ZRYY,DJBMID,DJBMMC,DZZBZID,DZZBZ,CLJG,GZFSSJ,QXRYID,QXRYMC,GZDCZJG,GZXZ,GZJT,GZLX,GZQK,SFTZ,GZTZSJ,ZDZZDZQK,GZXB,GZSDTQ,GZSSFH,GZDWXXMS,GZDWXXXZB,GZDWXXYZB,YDCS,CHZDZQK,GZDCZSJ,HFSDSJ,GZSBYXBZ,SFZJL,GLZJLID,BZ,CBSSJB,HJSSJB,RSSSJB,DWSSJB,SBSJ,JJBZJ,SFZNGZ,DJRID,DJRMC,GZLB,GZJB,GZSFYJ,GZTYFW,DYDJ,GZSSQK,GZTYFWID,GZTYFWMC,SSDWID,SSDWMC,CLRID,CLRMC,CLSJ,GZFXBG,SBLXBM,SBLX,TZYY1,TZYY2,GZLBT,GZDWLBJL,CLWC,GZFXBGLCID,GZFXBGLCHJ,GZFXBGSCSJ,TP,SFBS,JBSDZQK";
//$str2="OBJ_ID,SGYJQXD_ID,BDZID,BDZMC,SSDSID,SSDSMC,GZXLID,GZXLMC,GZSB,GZSBMC,JSYY,ZRYY,TZYY1,TZYY2,DJBMID,DJBMMC,DZZBZID,DZZBZ,CLJG,GZFSSJ,QXRYID,QXRYMC,GZDCZJG,GZXZ,GZJT,GZLX,GZQK,SFTZ,GZTZSJ,ZDZZDZQK,GZXB,GZSDTQ,GZSSFH,GZDWXXMS,GZDWXXXZB,GZDWXXYZB,YDCS,CHZDZQK,GZDCZSJ,HFSDSJ,GZSBYXBZ,SFZJL,GLZJLID,TP,BZ,CBSSJB,HJSSJB,RSSSJB,DWSSJB,SBSJ,JJBZJ,SFZNGZ,DJRID,DJRMC,GZLB,GZJB,GZSFYJ,GZTYFW,DYDJ,GZSSQK,GZTYFWID,GZTYFWMC,SSDWID,SSDWMC,CLRID,CLRMC,CLSJ,GZFXBG,SBLXBM,SBLX";
//
$str1="OBJ_ID,SJFL,SJSJ,SJYY,SJXCZL,CLCS,DJR,BZ,SJMC,SJFXR,SSDW,SSDWID,YWBZ,YWBZID,JBQK,DT,DG,TC,SDX,TXX,BYQ,DL,TDSJ,FSDD,LARQ,DJSJ,DJRID,SFPA,GISZB,DYDJ";
$str2="OBJ_ID,SJFL,SJSJ,SJYY,SJXCZL,FZCS,DJR,FJ,BZ";


//$str1="1,2";
//$str2="2,3";
$arr1=explode(",",$str1);//根据逗号将字符串分割为数组
$arr2=explode(",",$str2);

$arr_diff=array_diff($arr1,$arr2);//对比不同
echo json_encode(
    array(
        $arr_diff,
        "arr1" => count($arr1),
        "arr2" => count($arr2),
        "diff"=>count($arr_diff)
    )
);